#!/usr/bin/env bash
#

umask 022
unalias -a

pushd() { command pushd "$1" > /dev/null; }
popd() { command popd "$1" > /dev/null; }
msg() { printf "\033[1;34m::\033[0m %s\n" "$@"; }
warn() { printf "\033[1;33m::\033[0m %s\n" "$@"; }
die() { printf "\033[1;31m::\033[0m %s\n" "$@"; exit 1; }

usage() { exit 0; }

check_root() {
	if [[ $EUID -ne 0 ]]; then
		die "You must be root to run 'neko'"
	fi
}

get_filename() {
	local tgt

	if echo "$1" | grep -q -E '^((https|http|ftp|rtsp|mms|file)?:\/\/).+'; then
		tgt="$(basename $1)"
		echo "$SRCDEST/$tgt"
	else
		echo "$1"
	fi
}

create_zip() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.CreateZipArchive("$1", "$2")
	EOF
}

create_xz() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.CreateXZArchive("$1", "$2")
	EOF
}

unpack_zip() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.UnpackZipArchive("$1", "$2")
	EOF
}

unpack_xz() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.UnpackXZArchive("$1", "$2")
	EOF
}

list_zip() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.ListZipContents("$1")
	EOF
}

list_xz() {
	python3 <<-EOF
		import npk_archive as NekoArchive
		NekoArchive.ListXZContents("$1")
	EOF
}

parse_comment() {
	python3 <<-EOF
		import npk_parse as NekoParse
		NekoParse.CommentVariable("$1", "$2")
	EOF
}

parse_json() {
	python3 <<-EOF
		import npk_parse as NekoParse
		NekoParse.JsonVariable("$1", "$2", "$3")
	EOF
}

list_subtract() {
	(
		cat "$1" "$2" | sort | uniq -u
		cat "$1"
	) | sort | uniq -d
}

list_uninstall() {
	local f p
	local files=$(sort -r "$1" | sed 's:^:'"${ROOTDIR}/"': ; s:/^[^\.]\./::g; s:/\{2,\}:/:g; s:/\./:/:g')
	if [ -z "$DRYRUN" ] ; then
		echo "$files" | tr '\n' '\0' | xargs -0 rm 2>/dev/null
		echo "$files" | tr '\n' '\0' | xargs -0 rmdir 2>/dev/null
		[ "$2" ] && echo "$files" >> "$2"
	fi
	return 0
}

source_config() {
	if [ ! -f "$config" ]; then
		die "Failed to source the configuration file"
	fi

	source "$config"

	[ "$BARCH" ] || die "Specify CPU architecture"
}

source_recipe() {
	unset name version release options backup source noextract
	unset -f build
	local myport

	if [ -f "$topdir/KagamiBuild" ]; then
		myport="$topdir/KagamiBuild"
	elif [ -f "$topdir/Pkgfile" ]; then
		myport="$topdir/Pkgfile"
	else
		die "Failed to source the package recipe"
	fi

	source "$myport"

	depends="$(parse_comment $myport "Depends on")"
	conflicts="$(parse_comment $myport "Conflicts with")"
	summary="$(parse_comment $myport "Description")"
	url="$(parse_comment $myport "URL")"
	section="$(parse_comment $myport "Section")"
	priority="$(parse_comment $myport "Priority")"
	maintainer="$(parse_comment $myport "Maintainer" | sed -e 's/, / /g' | sed -e 's/ at /@/g' | sed -e 's/ dot /./')"

	if [ "$bootstrap" = "yes" ]; then
		if [ -z "$summary" ]; then
			summary="(null)"
		fi
		if [ -z "$section" ]; then
			section="misc"
		fi
	fi

	if [ -z "$name" ]; then
		die "The name of package is not set"
	elif [ -z "$version" ]; then
		die "The version of package is not set"
	elif [ -z "$release" ]; then
		die "The release of package is not set"
	elif [ -z "$summary" ]; then
		die "The summary of package is not set"
	elif [ -z "$section" ]; then
		die "The section of package is not set"
	fi
}

parse_options() {
	for myopts in ${OPTIONS[@]} ${options[@]}; do
		case $myopts in
			bootstrap) opt_bootstrap="1" ;;
			~bootstrap) opt_bootstrap="0" ;;
			ccache) opt_ccache="1" ;;
			~ccache) opt_ccache="0" ;;
			docs) opt_docs="1" ;;
			~docs) opt_docs="0" ;;
			emptydirs) opt_emptydirs="1" ;;
			~emptydirs) opt_emptydirs="0" ;;
			libtool) opt_libtool="1" ;;
			~libtool) opt_libtool="0" ;;
			locales) opt_locales="1" ;;
			~locales) opt_locales="0" ;;
			makeflags) opt_makeflags="1" ;;
			~makeflags) opt_makeflags="0" ;;
			strip) opt_strip="1" ;;
			~strip) opt_strip="0" ;;
		esac
	done
}

download_file() {
	local url="$1"

	if [ ! "`type -p curl`" ]; then
		die "curl wasn't found"
	fi

	msg "Downloading $url"

	LOCAL_FILENAME=`get_filename $FILE`
	LOCAL_FILENAME_PARTIAL="$LOCAL_FILENAME.partial"
	cmd="-f --retry 3 --retry-delay 3 -L -o $LOCAL_FILENAME_PARTIAL $CURLOPTS"
	resumecmd="-C -"
	fullcmd="curl $cmd"
	RESUME="no"

	if [ -f "$LOCAL_FILENAME_PARTIAL" ]; then
		warn "Partial download found, trying to resume"
		RESUME="yes"
		fullcmd="$fullcmd $resumecmd"
	fi

	error=1

	if [ $error != 0 ]; then
		while true; do
			$fullcmd $1
			error=$?
			if [ $error != 0 ] && [ "$RESUME" = "yes" ]; then
				warn "Partial download failed, restarting"
				rm -f "$LOCAL_FILENAME_PARTIAL"
				RESUME="yes"
			else
				break
			fi
		done
	fi

	if [ $error != 0 -o ! -f "$LOCAL_FILENAME_PARTIAL" ]; then
		die "Downloading '${1}' failed."
	fi

	mv -f "$LOCAL_FILENAME_PARTIAL" "$LOCAL_FILENAME"
}

download_source() {
	local FILE LOCAL_FILENAME tgt

	if [ -n "$source" ]; then
		for FILE in ${source[@]}; do
			if echo "$FILE" | grep -q -E '^((git)?:\/\/).+' || echo "$FILE" | grep -q -E '.*\.git$'; then
				tgt="$(basename $FILE)"
				if [ ! -d "$SRC/$tgt" ]; then
					msg "Clonning $FILE"
					git clone $GITOPTS $FILE "$SRC/$tgt"
				fi
			elif echo "$FILE" | grep -q -E '^((https|http|ftp|rtsp|mms)?:\/\/).+'; then
				LOCAL_FILENAME=`get_filename $FILE`
				if [ ! -e $LOCAL_FILENAME ]; then
					if [ "$LOCAL_FILENAME" = "$FILE" ]; then
						die "Source file '$LOCAL_FILENAME' not found (can not be downloaded, URL not specified)."
					else
						download_file $FILE
					fi
				fi
			fi
		done
	fi
}

unpack_source() {
	if [ "$source" ]; then
		for FILE in ${source[@]}; do
			FILENAME="$(basename $FILE)"
			LOCAL_FILENAME=`get_filename $FILE`

			for NOEXT in ${noextract[@]}; do
				if [ "$NOEXT" = "$FILENAME" ]; then
					nxt=1
					break
				fi
			done

			if [ "$FILENAME" != "$FILE" ] && [ "$nxt" != 1 ]; then
				case $LOCAL_FILENAME in
					*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.tar.lz|*.tlz|*.tar.lz4|*.tar.zst|*.tar.zstd|*.zip|*.rpm|*.7z)
						msg "Extacting $FILENAME to the sources directory"
						bsdtar -p -o -C "$SRC" -xf $LOCAL_FILENAME || die "Failed to extract $FILENAME to the sources directory"
						;;
					*)
						msg "Copying $FILENAME to the sources directory"
						cp $LOCAL_FILENAME "$SRC" || die "Failed to copy $FILENAME to the sources directory"
						;;
				esac
			else
				msg "Copying $FILENAME to the sources directory"
				cp $LOCAL_FILENAME "$SRC" || die "Failed to copy $FILENAME to the sources directory"
			fi
			nxt=
		done
	fi
}

run_strip() {
	local fs="$1"

	( cd "$fs"
		find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs ${CROSS_COMPILE}strip --strip-all 2>/dev/null
		find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs ${CROSS_COMPILE}strip --strip-unneeded 2>/dev/null
		find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs ${CROSS_COMPILE}strip --strip-debug 2>/dev/null
	)
}

setup_compiler() {
	if [ -n "$CC" ]; then
		MYCC="$CC"
	else
		MYCC="gcc"
	fi
	if [ -n "$CXX" ]; then
		MYCXX="$CXX"
	else
		MYCXX="g++"
	fi
}

compile_package() {
	if [ "$opt_makeflags" != "0" ]; then
		export MAKEFLAGS="$MKOPTS"
		export NINJA_OPTIONS="$MKOPTS"
	fi

	if [ "$bootstrap" != "yes" ]; then
		if [ "$opt_cache" != "0" ]; then
			if type ccache > /dev/null 2>&1; then
				if [ -n "$CC" ]; then
					MYCC="ccache $CC"
				else
					MYCC="ccache gcc"
				fi
				if [ -n "$CXX" ]; then
					MYCXX="ccache $CXX"
				else
					MYCXX="ccache g++"
				fi
			else
				setup_compiler
			fi
		else
			setup_compiler
		fi
	fi

	if type build > /dev/null 2>&1; then
		msg "Compiling package"
		pushd "$SRC"
			(
				set -e
				export CC="$MYCC"
				export CXX="$MYCXX"
				build
			)
			if [ $? -ne 0 ]; then
				die  "Failed to compile package: $name"
			fi
		popd
	fi

	pushd "$PKG"
		msg "Removing junk from package"
		rm -rf {,usr/}{,local/}{,share/}info usr{,/local}{,/share},opt/*}/info
		rm -rf {,usr/}{,local/}lib/charset.alias

		find . -name "*.pod" -print0 | xargs -0 rm -rf
		find . -name ".packlist" -print0 | xargs -0 rm -rf

		if [ "$opt_libtool" = "0" ]; then
			msg "Removing libtool files"
			find . -name "*.la" -print0 | xargs -0 rm -rf
		fi

		if [ "$opt_emptydirs" = "0" ]; then
				msg "Removing empty directories"
				find . -maxdepth 3 -type d -exec rmdir {} + 2>/dev/null
		fi

		if [ "$opt_locales" = "0" ]; then
			msg "Removing locales"
			rm -rf {,usr/}{,local/}{,share/,lib/}locale
		fi

		if [ "$opt_docs" = "0" ]; then
			msg "Removing documentation"
			rm -rf {,usr/}{,local/}{,share/}doc usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc}
		fi

		if [ -d "$PKG/usr/share/help" ]; then
			pushd usr/share/help
				mv C "$SRC"/

				rm -rf *

				mv "$SRC"/C .
			popd
		fi

		if [ "$opt_strip" != "0" ]; then
			msg "Removing debug information from binary files"
			run_strip "$PKG"
		fi

		msg "Compressing manual pages"
		if [ -d "$PKG/usr/share/man" ]; then
			(
				cd "$PKG/usr/share/man"
				find . -type f -exec pigz -9 '{}' +
				find . -type l | while read -r file; do
					ln -sf "$(readlink -- "$file").gz" "${file}.gz"
					rm "$file"
				done
			)
		fi
	popd
}


create_package() {
	local toinclude="manifest.json"
	mkdir -p "$WORK/final"

	pushd "$WORK"
		pushd "$PKG"
			msg "Compressing package data"
			create_xz . "$WORK"/install.tar.xz

			find $(ls) >> "$WORK"/files.txt

			toinclude+=" install.tar.xz files.txt"
		popd

		msg "Generating metadata"
		if [ -z "$priority" ]; then
			priority="optional"
		fi

		: > "$WORK"/manifest.json

		echo '{' >> "$WORK"/manifest.json
		echo -e '\t"summary": {' >> "$WORK"/manifest.json
		echo -e '\t\t"name": "'${name}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"version": "'${version}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"release": "'${release}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"priority": "'${priority}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"summary": "'${summary}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"section": "'${section}'",' >> "$WORK"/manifest.json
		[ "$url" ] && echo -e '\t\t"homepage": "'${url}'",' >> "$WORK"/manifest.json
		echo -e '\t\t"maintainer": "'${maintainer}'"' >> "$WORK"/manifest.json
		echo -e '\t}' >> "$WORK"/manifest.json
		echo '}' >> "$WORK"/manifest.json

		if [ -n "$backup" ]; then
			for a in ${backup[@]}; do
				echo "$a" >> "$WORK"/backup
			done

			toinclude+=" backup"
		fi

		if [ -f "$topdir/install" ]; then
			install -Dm0755 "$topdir/install" "$WORKDIR/install"

			toinclude+=" install"
		fi

		for i in $toinclude; do
			mv "$WORK"/$i "$WORK/final"/$i
		done

		pushd "$WORK/final"
			create_zip . "$TARGET"
			if [ $? -ne 0 ]; then
				die "Failed to create package"
			fi
		popd

		msg "Package was successfuly built"
	popd
}

npk_build() {
	source_recipe

	if [ -z "$PKGDEST" ]; then
		PKGDEST="$topdir"
	fi
	if [ -z "$SRCDEST" ]; then
		SRCDEST="$topdir"
	fi

	TARGET="$PKGDEST/$name-$version-$release.$BARCH.npk"

	if [ "$force" = "yes" ]; then
		rm -rf "$TARGET"
	fi

	if [ ! -f "$TARGET" ]; then
		msg "Building package: $name"
		WORK="$PWD/work"
		PKG="$WORK/pkg"
		SRC="$WORK/src"

		rm -rf "$WORK"
		mkdir -p "$PKG" "$SRC"

		parse_options

		if [ "$bootstrap" = "yes" ]; then
			if [ "$opt_bootstrap" = "0" ]; then
				die "This package couldn't be built in the cross environment"
			fi
		fi

		if [ "$download" != "no" ]; then
			download_source
		fi

		if [ "$extract" != "no" ]; then
			unpack_source
		fi

		if [ "$build" != "no" ]; then
			compile_package
		fi

		if [ "$package" != "no" ]; then
			create_package
			if [ "$clean" != "no" ]; then
				rm -rf "$WORK"
			fi
		fi
	else
		warn "Package have already built"
		return 0
	fi
}

run_backup() {
	local backup="$1"
	local action="$2"
	local mybackup

	if [ -f "$backup" ]; then
		case $action in
			save)
				msg "Saving files for backup"
				while IFS= read -r mybackup; do
					if [ -f "$ROOTDIR/$mybackup" ]; then
						mv "$ROOTDIR/$mybackup" "$ROOTDIR/$mybackup.bak" || die "Failed to save file: ${mybackup}"
					fi
				done < "$backup"
				;;
			restore)
				msg "Restoring old files"
				while IFS= read -r mybackup; do
					if [ -f "$ROOTDIR/$mybackup.bak" ]; then
						if [ -f "$ROOTDIR/$mybackup" ]; then
							mv "$ROOTDIR/$mybackup" "$ROOTDIR/$mybackup.new" || die "Failed to save new file: ${mybackup}"
						fi
						mv "$ROOTDIR/$mybackup.bak" "$ROOTDIR/$mybackup" || die "Failed to restore file: ${mybackup}"
					fi
				done < "$backup"
				;;
		esac
	fi
}

run_scripts() {
	local script="$1"
	local action="$2"

	if [ -x "$script" ]; then
		cp "$script" "$ROOTDIR/install"
		msg "Running $action script"
		xchroot "${ROOTDIR}/" /install $action
		rm -rf "$ROOTDIR/install"
	fi
}

npk_install() {
	if [ "$TARGET" ]; then
		local pkg="$TARGET"
	else
		local pkg="$1"
	fi

	[ ! -f "$pkg" ] && die "Your package file was not found or not specified"
	[ "${pkg##*.}" != "npk" ] && die "This file does not end in .npk"

	[ -z "$(list_zip $pkg | grep -oh 'manifest.json')" ] && die "It is not a neko package"

	if [ "$rootdir" ] && [ ! -d "$rootdir" ]; then
		mkdir -p "$rootdir"
	fi

	tmpdir="$(mktemp -d)" || die "Couldn't create a temporary directory"
	unpack_zip "$tmpdir" "$pkg"

	local localname="$(parse_json $tmpdir/manifest.json summary name)"
	local localver="$(parse_json $tmpdir/manifest.json summary version)"
	local localrel="$(parse_json $tmpdir/manifest.json summary release)"

	[ -z "$localname" ] && die "Your package is broken"

	if [ -f "${rootdir}${DBDIR}/$localname/manifest.json" ]; then
		if [ "$needed" = "yes" ]; then
			warn "$localname: This package has been already installed"
			return 0
		else
			msg "Updating package: $localname"
			local update="true"
		fi
	else
		msg "Installing package: $localname"
		local update="false"
	fi

	trap "" INT

	if [ "$force" != "yes" ] && [ "$update" != "true" ]; then
		msg "Checking for file conflicts"
		if [ ! -f "${rootdir}${DBDIR}/$localname/manifest.json" ]; then
			for fileconflicts in $(list_xz $tmpdir/install.tar.xz); do
				if [ -f "$rootdir/$fileconflicts" ] || [ -L "$rootdir/$fileconflicts" ]; then
					echo "$fileconflicts" >> /tmp/conflicts
				fi
			done
			if [ -f "/tmp/conflicts" ]; then
				warn "Following files couldn't be overwritten"
				cat /tmp/conflicts
				exit 1
			fi
		fi
	fi

	if [ "$scripts" != "no" ]; then
		if [ -f "$tmpdir/install" ]; then
			run_scripts "$tmpdir/install" pre-install
		fi
	fi
	if [ "$backup" != "no" ]; then
		if [ -f "$tmpdir/backup" ]; then
			run_backup "$tmpdir/backup" save
		fi
	fi

	msg "Extracting package"
	unpack_xz "${rootdir}/" "$tmpdir/install.tar.xz"
	if [ $? -ne 0 ]; then
		die "Failed to extract package"
	fi

	if [ "$update" = "true" ]; then
		if [ -f "$tmpdir/files.txt" ] && [ -f "${ROOTDIR}${DBDIR}/$localname/files" ]; then
			msg -1 "Removing old files"
			list_subtract "${ROOTDIR}${DBDIR}/$localname/files" "$tmpdir/files.txt" | list_uninstall - || true
		fi
	fi

	if [ "$backup" != "no" ]; then
		if [ -f "$tmpdir/backup" ]; then
			run_backup "$tmpdir/backup" restore
		fi
	fi

	if [ "$scripts" != "no" ]; then
		if [ -f "$tmpdir/install" ]; then
			run_scripts "$tmpdir/install" post-install
		fi
	fi

	msg "Installing package info"
	if [ "$update" = "true" ]; then
		rm -rf "${rootdir}${DBDIR}/$localname"
		mkdir -p "${rootdir}${DBDIR}/$localname"
	else
		mkdir -p "${rootdir}${DBDIR}/$localname"
	fi

	for files in manifest.json files.txt backup install; do
		if [ -f "$tmpdir/$files" ]; then
			install -Dm0644 "$tmpdir/$files" "${rootdir}${DBDIR}/$localname/$files"
		fi
	done

	#run_triggers $localname

	rm -rf "$tmpdir" "/tmp/conflicts" "$rootdir/install"
	msg "Package was successfully installed"

	trap INT
}

main() {
	topdir="$PWD"
	config="/etc/neko/make.conf"
	OPTIONS=('emptydirs' 'strip' 'makeflags' 'locales' 'docs' 'ccache' 'libtool' '~bootstrap' '~embedded')

	force="no"
	bootstrap="no"
	needed="no"
	depends="yes"
	conflicts="yes"
	backup="yes"
	scripts="yes"
	triggers="yes"
	clean="yes"
	download="yes"
	extract="yes"
	build="yes"
	package="yes"

	case $1 in
		build|bi) shift; mode="npk_build" ;;
		emerge|em) shift; mode="npk_emerge" ;;
		info|if) shift; mode="npk_info" ;;
		install|in) shift; mode="npk_install" ;;
		list|li) shift; mode="npk_list" ;;
		remove|rm) shift; mode="npk_remove" ;;
		search|sr) shift; mode="npk_search" ;;
		sync|sy) shift; mode="npk_sync" ;;
		upgrade|up) shift; mode="npk_upgrade" ;;
		version) version ;;
		*|help) usage ;;
	esac

	while getopts :fwndebstCDEBPc:r: opts; do
		case $opts in
			c) config="$(realpath $OPTARG)" ;;
			r) rootdir="$(realpath $OPTARG)"; rootdir="${rootdir%/}" ;;
			f) force="yes" ;;
			w) bootstrap="yes" ;;
			n) needed="yes" ;;
			d) depends="no" ;;
			e) conflicts="no" ;;
			b) backup="no" ;;
			s) scripts="no" ;;
			t) triggers="no" ;;
			C) clean="no" ;;
			D) download="no" ;;
			E) extract="no" ;;
			B) build="no" ;;
			P) package="no" ;;
		esac
	done
	shift $((OPTIND - 1))

	check_root
	source_config

	if [ "$mode" = "npk_upgrade" ] || [ "$mode" = "npk_sync" ] || [ "$mode" = "npk_build" ]; then
		$mode
	else
		for pkg in "$@"; do
			$mode $pkg
		done
	fi
}

main "$@"

exit 0

